#!/bin/bash
NARGS=$#
NF=$1
NS=$2
LXC_PATH=/var/lib/lxc
INTEGER='^[0-9]+$'

start_basic_test()
{
	if [ "$UID" -ne 0 ]; then
	echo "This script should be run as 'root'"; return 1
	fi

	if [[ $NARGS -ne 2 ]]; then
	echo "usage: $0 <N_FAST_CLIENTS> <N_SLOW_CLIENTS>"
	return 1
	fi

	if ! [[ $NF =~ $INTEGER ]]; then
   	echo "error: Number of fast clients must be a number" >&2; return 1
	fi

	if ! [[ $NS =~ $INTEGER ]]; then
   	echo "error: Number of slow clients must be a number" >&2; return 1
	fi

	# Make script for clients and server
	cat >$LXC_PATH/buffer/rootfs/server_script <<'EOF'
#!/bin/bash
VLC_PATH=/home/jcarrera/Documents/vlc
export DISPLAY=
EOF
	
	chmod +x $LXC_PATH/buffer/rootfs/server_script

	for (( i=0; i < $NF; i++ ))
	do
		cat >$LXC_PATH/fast-client-${i}/rootfs/client_script <<'EOF'
#!/bin/bash
VLC_PATH=/home/jcarrera/Documents/vlc
export DISPLAY=
EOF
		
		chmod +x $LXC_PATH/fast-client-${i}/rootfs/client_script
	done

	for (( i=0; i < $NS; i++ ))
	do
		cat >$LXC_PATH/slow-client-${i}/rootfs/client_script <<'EOF'
#!/bin/bash
VLC_PATH=/home/jcarrera/Documents/vlc
export DISPLAY=
EOF
		
		chmod +x $LXC_PATH/slow-client-${i}/rootfs/client_script
	done

	# Configure default gateway
	echo "route add default gw 10.10.0.1 dev eth0" >> $LXC_PATH/buffer/rootfs/server_script
	echo 'sudo -u ubuntu $VLC_PATH/vlc -vvv $VLC_PATH/big_buck_bunny_480p_surround-fix.avi --sout "#transcode{vcodec=mjpg,venc=ffmpeg{qmin=10,qmax=10}}:standard{access=http{use-algorithms,allocation=MAX,replacement=NF,frame-buffers=10},mux=mpjpeg,dst=@:8080}"' >> $LXC_PATH/buffer/rootfs/server_script

	for (( i=0; i < $NF; i++ ))
	do
		echo "route add default gw 10.$(($i / 256 + 20)).$(($i % 256)).1 dev eth0" >> $LXC_PATH/fast-client-${i}/rootfs/client_script
		echo 'su - ubuntu -c "$VLC_PATH/vlc "--avcodec-error-resilience=3" --no-video http://10.10.0.2:8080"' >> $LXC_PATH/fast-client-${i}/rootfs/client_script
		echo "sleep 3" >> $LXC_PATH/fast-client-${i}/rootfs/client_script
	done

	for (( i=0; i < $NS; i++ ))
	do
		echo "route add default gw 10.$(($i / 256 + 30)).$(($i % 256)).1 dev eth0" >> $LXC_PATH/slow-client-${i}/rootfs/client_script
		echo 'su - ubuntu -c "$VLC_PATH/vlc "--avcodec-error-resilience=3" --no-video http://10.10.0.2:8080"' >> $LXC_PATH/slow-client-${i}/rootfs/client_script
		echo "sleep 3" >> $LXC_PATH/slow-client-${i}/rootfs/client_script
	done

	# Open ns-3 and start topology
	cd ns-3.19
	./waf build
	./waf --run "scratch/CameraStreaming --nsClients=$NS --nfClients=$NF --duration=3600" &
	sleep 5

	# Start server and clients script
	xterm -e lxc-start -n buffer ./server_script -c /dev/null &
	sleep 3

	for (( i=0; i < $NF; i++ ))
	do
		sleep 1
		xterm -e lxc-start -n fast-client-${i} ./client_script -c /dev/null &
	done

	for (( i=0; i < $NS; i++ ))
	do
		sleep 1
		xterm -e lxc-start -n slow-client-${i} ./client_script -c /dev/null &
	done

}

start_basic_test

