## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
SRC_PATH="/home/jcarrera/Documents/vlc/contrib/native/libvpx"
SRC_PATH_BARE=/home/jcarrera/Documents/vlc/contrib/native/libvpx
BUILD_PFX=
TOOLCHAIN=x86-linux-gcc
ASM_CONVERSION=/home/jcarrera/Documents/vlc/contrib/native/libvpx/build/make/ads2gas.pl

CC=gcc
AR=ar
LD=gcc
AS=yasm
STRIP=strip
NM=nm

CFLAGS  =  -m32 -fomit-frame-pointer -O3 -fPIC -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wpointer-arith -Wtype-limits -Wcast-qual -Wno-unused-function
ARFLAGS = -rus$(if $(quiet),c,v)
LDFLAGS =  -m32
ASFLAGS =  -f elf32
extralibs =  -lpthread
AS_SFX    = .asm
fmt_deps = sed -e 's;^\([a-zA-Z0-9_]*\)\.o;$(dir $@)\1$(suffix $<).o $@;'
ARCH_X86=yes
HAVE_MMX=yes
HAVE_SSE=yes
HAVE_SSE2=yes
HAVE_SSE3=yes
HAVE_SSSE3=yes
HAVE_SSE4_1=yes
HAVE_VPX_PORTS=yes
HAVE_STDINT_H=yes
HAVE_PTHREAD_H=yes
HAVE_SYS_MMAN_H=yes
HAVE_UNISTD_H=yes
CONFIG_GCC=yes
CONFIG_PIC=yes
CONFIG_FAST_UNALIGNED=yes
CONFIG_MD5=yes
CONFIG_RUNTIME_CPU_DETECT=yes
CONFIG_POSTPROC=yes
CONFIG_MULTITHREAD=yes
CONFIG_VP8_ENCODER=yes
CONFIG_VP8=yes
CONFIG_ENCODERS=yes
CONFIG_SPATIAL_RESAMPLING=yes
CONFIG_STATIC=yes
CONFIG_OS_SUPPORT=yes
HAVE_GNU_STRIP=yes
